#!/bin/bash
# 1) This script open the compressed files from EC_Earth (in the folder ../data):
# - one type of file (historic or future, coupled or uncoupled
# - for a range of years (each file contains 12 time steps corresponding to monthly values)
# 2) extract salinity, or temperature, ice concentration, mixed layer depth..
# 3) make yearly means (saved in a folder named after the variable extracted)
# 4) merge these into one file
# 5) select arctic region
# 6) send it to local computer
# 7) delete the uncompressed file


#----------------
# TO BE MODIFIED:
#----------------
run='Uncoupled'                                  #coupled or uncoupled
y1=1950                                        #min 1950
y2=2100                                        #max 2100
var='V'                                       #sal,temp,iceC,ML
#________________________________________________________________________
path_to_data='../../data/'

if [ $var ==  'V' ]
then
  subfolder='grid_V'
  var_code='vomecrty'
elif [ $var ==  'ML' ]
then
  subfolder='grid_T'
  var_code='somxl010'
elif [ $var ==  'TS' ]
then
  subfolder='grid_T'
  var_code='votemper,vosaline,somxl010,soicecov'
fi

if [ $run == 'Uncoupled' ]
then
  yh=2006
  preh='DHIn01'
  pref='DR8n01'
elif [ $run == 'Coupled' ]
then
  yh=2005
  preh='PISMhis'
  pref='rcp8.5_PISM'
fi

rm $var$run
mkdir $var$run

for y in $(seq $y1 $y2)
  do

  if [ $y -le $yh ]
  then
    pre=$preh
  else
    pre=$pref
  fi

  echo $y
  tar -xvf "$path_to_data$pre"_ORCA1_"$y".tar ORCA1_MM_"$y"_"$subfolder".nc
  cdo -yearmean -selvar,$var_code ORCA1_MM_"$y"_"$subfolder".nc "$var$run"/"$pre"_"$y"_yearly.nc 
  rm ORCA1_MM_"$y"_"$subfolder".nc
done

cdo mergetime "$var$run"/*_yearly.nc tempo.nc  
cdo sellonlatbox,-80,10,20,60 tempo.nc V_AtlSection_yearlyMeans_"$run".nc
rm tempo.nc
